쿠버네티스 인 액션 - Pod 학습
hotkimho/edu-backend pull request #3
Opened 2024-06-13 08:50 UTC by hotkimho

- 쿠버네티스 인 액션 ch03 pod 학습

2024-06-13 09:14 UTC, devmjkim commented
#2 PR 과 커밋이 중복됩니다. k8s-overveiw 브랜치를 base로 가져오시면 안되고 main에서 가져와야합니다.
pod 관련 커밋만 남을 수 있도록 정리해주세요.

2024-06-13 11:13 UTC, hotkimho commented
말씀해주신 대로 수정했습니다.
브랜치를 잘못 따와서 죄송합니다.

2024-06-14 08:13 UTC, devmjkim commented
사이드카 패턴 포함하여 멀티 컨테이너 패턴에 대해서 예시와 함께 내용 추가해주세요.

2024-06-14 08:31 UTC, devmjkim requested changes

2024-06-14 08:31 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +### 사이드카 컨테이너
멀티 컨테이너 패턴을 따로 문서로 작성해주세요.

2024-06-16 23:15 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +### 사이드카 컨테이너
멀티 컨테이너 패턴 별도의 문서로 작성했습니다.

2024-06-17 06:12 UTC, devmjkim requested changes

2024-06-17 06:12 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +`kubectl get pods`
kubectl command에 대한 정보는 `--help` 옵션으로 확인 가능합니다.
kubectl get pods는 특정 리소스를 조회하지 않는다면 해당 리소스 목록을 조회합니다. 
그리고 namespace scope의 리소스가 `-n` 옵션 없이 조회하는 경우 `default` 네임스페이스의 리소스를 조회합니다.
`--v` 옵션의 경우 로깅 관련 옵션 인 것 같은데 `kubectl logs` 옵션에도 없네요.
작성한 설명이 잘못되어 수정 부탁드리며 아래 `kubectl get` 옵션에 대해서도 스터디해주세요.

```
kubectl get --help
Display one or many resources.

 Prints a table of the most important information about the specified resources. You can filter the list using a label
selector and the --selector flag. If the desired resource type is namespaced you will only see results in your current
namespace unless you pass --all-namespaces.

 By specifying the output as 'template' and providing a Go template as the value of the --template flag, you can filter
the attributes of the fetched resources.

Use "kubectl api-resources" for a complete list of supported resources.

Examples:
  # List all pods in ps output format
  kubectl get pods

  # List all pods in ps output format with more information (such as node name)
  kubectl get pods -o wide

  # List a single replication controller with specified NAME in ps output format
  kubectl get replicationcontroller web

  # List deployments in JSON output format, in the "v1" version of the "apps" API group
  kubectl get deployments.v1.apps -o json

  # List a single pod in JSON output format
  kubectl get -o json pod web-pod-13je7

  # List a pod identified by type and name specified in "pod.yaml" in JSON output format
  kubectl get -f pod.yaml -o json

  # List resources from a directory with kustomization.yaml - e.g. dir/kustomization.yaml
  kubectl get -k dir/

  # Return only the phase value of the specified pod
  kubectl get -o template pod/web-pod-13je7 --template={{.status.phase}}

  # List resource information in custom columns
  kubectl get pod test-pod -o custom-columns=CONTAINER:.spec.containers[0].name,IMAGE:.spec.containers[0].image

  # List all replication controllers and services together in ps output format
  kubectl get rc,services

  # List one or more resources by their type and names
  kubectl get rc/web service/frontend pods/web-pod-13je7

  # List the 'status' subresource for a single pod
  kubectl get pod web-pod-13je7 --subresource status

Options:
    -A, --all-namespaces=false:
	If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even
	if specified with --namespace.

    --allow-missing-template-keys=true:
	If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to
	golang and jsonpath output formats.

    --chunk-size=500:
	Return large lists in chunks rather than all at once. Pass 0 to disable. This flag is beta and may change in
	the future.

    --field-selector='':
	Selector (field query) to filter on, supports '=', '==', and '!='.(e.g. --field-selector
	key1=value1,key2=value2). The server only supports a limited number of field queries per type.

    -f, --filename=[]:
	Filename, directory, or URL to files identifying the resource to get from a server.

    --ignore-not-found=false:
	If the requested object does not exist the command will return exit code 0.

    -k, --kustomize='':
	Process the kustomization directory. This flag can't be used together with -f or -R.

    -L, --label-columns=[]:
	Accepts a comma separated list of labels that are going to be presented as columns. Names are case-sensitive.
	You can also use multiple flag options like -L label1 -L label2...

    --no-headers=false:
	When using the default or custom-column output format, don't print headers (default print headers).

    -o, --output='':
	Output format. One of: (json, yaml, name, go-template, go-template-file, template, templatefile, jsonpath,
	jsonpath-as-json, jsonpath-file, custom-columns, custom-columns-file, wide). See custom columns
	[https://kubernetes.io/docs/reference/kubectl/#custom-columns], golang template
	[http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template
	[https://kubernetes.io/docs/reference/kubectl/jsonpath/].

    --output-watch-events=false:
	Output watch event objects when --watch or --watch-only is used. Existing objects are output as initial ADDED
	events.

    --raw='':
	Raw URI to request from the server.  Uses the transport specified by the kubeconfig file.

    -R, --recursive=false:
	Process the directory used in -f, --filename recursively. Useful when you want to manage related manifests
	organized within the same directory.

    -l, --selector='':
	Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2). Matching
	objects must satisfy all of the specified label constraints.

    --server-print=true:
	If true, have the server return the appropriate table output. Supports extension APIs and CRDs.

    --show-kind=false:
	If present, list the resource type for the requested object(s).

    --show-labels=false:
	When printing, show all labels as the last column (default hide labels column)

    --show-managed-fields=false:
	If true, keep the managedFields when printing objects in JSON or YAML format.

    --sort-by='':
	If non-empty, sort list types using this field specification.  The field specification is expressed as a
	JSONPath expression (e.g. '{.metadata.name}'). The field in the API resource specified by this JSONPath
	expression must be an integer or a string.

    --subresource='':
	If specified, gets the subresource of the requested object. Must be one of [status scale]. This flag is beta
	and may change in the future.

    --template='':
	Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format
	is golang templates [http://golang.org/pkg/text/template/#pkg-overview].

    -w, --watch=false:
	After listing/getting the requested object, watch for changes.

    --watch-only=false:
	Watch for changes to the requested object(s), without listing/getting first.

Usage:
  kubectl get
[(-o|--output=)json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file|custom-columns|custom-columns-file|wide]
(TYPE[.VERSION][.GROUP] [NAME | -l label] | TYPE[.VERSION][.GROUP]/NAME ...) [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

2024-06-17 06:12 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +API 서버와 통신하기 위한 설정을 불러온다. 서버 정보, 클러스터 정보, 인증서 등등을 가지며 아래에 있는 내용은 실제 kubeconfig 파일의 내용이다.
kubeconfig에서 인증은 사용자 인증서나 토큰을 사용할 수 있어 kubeconfig 파일에 토큰도 포함될 수 있습니다.

2024-06-17 06:12 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +레이블은 쿠버네티스 오브젝트(pod, deployment)에 첨부된 (키, 값) 형태의 값이다.
레이블은 모든 kubernetes 객체에서 사용할 수 있습니다.

2024-06-17 06:12 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +`kubectl delete pod {pod name}` 명령어가 실행되면, 쿠버네티스 API 서버에 파드 요청을 보냄
`kubectl delete pod {pod name}` -> `kubectl delete pod {pod name} -n {namespace}`

2024-06-17 07:30 UTC, hotkimho commented
2024.06.17 리뷰 보충할 내용
- kubectl get 옵션
- known label 
- 레이블, 어노테이션 차이
- Init 컨테이너
- 컨테이너 리소스 제한
- image pull policy
- 라이브니스, 레디니스 프로브

2024-06-17 14:07 UTC, hotkimho reviewed
2024.06.17 리뷰 하면서 추가적으로 알아야 하는 내용들 추가 했습니다.

2024-06-20 01:19 UTC, devmjkim commented
> 2024.06.17 리뷰 하면서 추가적으로 알아야 하는 내용들 추가 했습니다.

코멘트에 대한 답변 달아주세요. 해당 내용을 수정했다면 수정 사항도 같이 작성해주세요.

2024-06-20 01:33 UTC, hotkimho commented
> 2024.06.17 리뷰 하면서 추가적으로 알아야 하는 내용들 추가 했습니다.

2024-06-20 02:15 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +`kubectl get pods`
> kubectl command에 대한 정보는 --help 옵션으로 확인 가능합니다.
kubectl get pods는 특정 리소스를 조회하지 않는다면 해당 리소스 목록을 조회합니다.
그리고 namespace scope의 리소스가 -n 옵션 없이 조회하는 경우 default 네임스페이스의 리소스를 조회합니다.
--v 옵션의 경우 로깅 관련 옵션 인 것 같은데 kubectl logs 옵션에도 없네요.
작성한 설명이 잘못되어 수정 부탁드리며 아래 kubectl get 옵션에 대해서도 스터디해주세요.

1. --v 옵션의 경우 `get`, `logs` 옵션에 포함되지 않은 kubectl 에서 제공하는 옵션입니다.
- `kubectl <명령> v <log level(1~9)>`
- `kubectl <명령> --v=<log level(1~9)>`
- `kubectl get pod -n default v 9`: 디폴트 네임스페이스에서 파드 조회 및 조회되는 과정 로깅

형식으로 사용하여 로그 레벨에 관해서는 아래에 정의되어 있습니다.

| 로그 레벨 | 세부 사항 |
|-----------|------------|
| --v=0     | 일반적으로 클러스터 운영자(operator)에게 항상 보여지게 하기에는 유용함. |
| --v=1     | 자세한 정보를 원하지 않는 경우, 적절한 기본 로그 수준. |
| --v=2     | 서비스와 시스템의 중요한 변화와 관련이 있는 중요한 로그 메시지에 대한 유용한 정상 상태 정보. 이는 대부분의 시스템에서 권장되는 기본 로그 수준이다. |
| --v=3     | 변경 사항에 대한 확장 정보. |
| --v=4     | 디버그 수준 상세화. |
| --v=5     | 트레이스 수준 상세화. |
| --v=6     | 요청한 리소스를 표시. |
| --v=7     | HTTP 요청 헤더를 표시. |
| --v=8     | HTTP 요청 내용을 표시. |
| --v=9     | 내용을 잘라 내지 않고 HTTP 요청 내용을 표시. |

참고링크 : [쿠버네티스 치트시트](https://kubernetes.io/ko/docs/reference/kubectl/cheatsheet/)
참고링크 : [쿠버네티스 kubectl 문서](https://kubernetes.io/docs/reference/kubectl/kubectl/)

2. `get` 옵션 학습
kubectl get 옵션은 쿠버네티스의 리소스를 조회할 때 사용하며, `kubectl get <resource-type> <option> <resource-name>` 형식으로 사용됩니다.
작성한 명령어는 특정 네임스페이스를 지정하지 않는 이상 `default` 네임스페이스 기준으로 작성했습니다.

자주 사용되는 get 명령어의 옵션을 정리
- option
  - o(출력 형식 지정)
    - wide: 추가 정보를 출력
      - kubectl get pods -o wide
    - json: JSON 형식 출력
      - kubectl get pods -o json
    - yaml: YAML 형식 출력
      - kubectl get pods -o yaml
  - w(실시간으로 변경 사항 감지, 종료되지 않고 계속 감시)
    - kube get pods -w
  - l(레이블 셀렉터)
    - 특정 레이블을 가진 리소스만 조회
    - kubectl get pods -l key=value
  - --all-namespaces
    - 모든 네임스페이스의 리소스 조회
    - kubectl get pods --all-namespaces
  - n(네임 스페이스 명시)
    - 옵션을 사용하지 않을 경우 `default` 네임스페이스 사용
    - kubectl get pods -n my-namespace
    - kubectl get pods -n kube-system
  - 유용한 옵션
    - kubectl get pods --show-labels: 모든 파드의 레이블 조회
    - kubectl get events --sort-by=.metadata.creationTimestamp: 타임스탬프로 정렬된 이벤트 조회
    - kubectl events --types=Warning: 모든 Warning 타입 이벤트 조회
    - kubectl get pods --field-selector=status.phase=Running -n <namespace>: 네임스페이스의 모든 실핼중인 파드 조회

참고링크 : [쿠버네티스 치트시트](https://kubernetes.io/ko/docs/reference/kubectl/cheatsheet/)

2024-06-20 06:05 UTC, hotkimho commented
초기화 컨테이너 실습
로깅 분리
리소스 제한 요청, 제한 디폴트 (제한을 초과하는 컨테이너는 어떻게 조절되나?)
어노테이션 실제 저장되는 값 확인해보기(쿠버네티스)
이미지 정책 디폴트
각종 설정들 디폴트
공부한것들 실습(실패 케이스)
레디니스 프로브
kubectx

2024-06-20 07:41 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +API 서버와 통신하기 위한 설정을 불러온다. 서버 정보, 클러스터 정보, 인증서 등등을 가지며 아래에 있는 내용은 실제 kubeconfig 파일의 내용이다.
kubeconfig 내용 보충하여 추가 했습니다.

2024-06-20 07:43 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +레이블은 쿠버네티스 오브젝트(pod, deployment)에 첨부된 (키, 값) 형태의 값이다.
해당 내용 `레이블은 쿠버네티스 모든 오브젝트에 첨부된 (키, 값) 형태의 값이다.` 로 수정하였습니다.

2024-06-20 07:45 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +`kubectl delete pod {pod name}` 명령어가 실행되면, 쿠버네티스 API 서버에 파드 요청을 보냄
`kubectl delete pod {pod name} -n {namespace}`로 수정해서 다시 업로드 하였습니다.

2024-06-23 17:11 UTC, hotkimho commented
2024.06.20 리뷰 보충
추가한 내용
- 초기화 컨테이너 내용 보충
- 컨테이너 상태
- 컨테이너 라이프사이클 훅
- 리소스 관리
- 이미지 기본 정책 테스트 추가
- 파드 상태
- 파드 컨디션
- 라이브니스 프로브
- 레디니스 프로브 
- 어노테이션 사용 데이터 조회
- 디플로이먼트 조회

2024-06-24 02:06 UTC, hotkimho commented
> ### 리뷰 대기
> 2024.06.20 리뷰 보충 추가한 내용
> 
> * 초기화 컨테이너 내용 보충
> * 컨테이너 상태
> * 컨테이너 라이프사이클 훅
> * 리소스 관리
> * 이미지 기본 정책 테스트 추가
> * 파드 상태
> * 파드 컨디션
> * 라이브니스 프로브
> * 레디니스 프로브
> * 어노테이션 사용 데이터 조회
> * 디플로이먼트 조회

리뷰 대기중인 PR입니다.

2024-06-24 02:59 UTC, devmjkim reviewed
pod외 커밋들은 제거해주세요.
코멘트 확인해주세요.

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +[1. 파드 기본 개념](#파드-기본-개념)
주제별로 목차를 묶어서 보여주세요.
목차가 있어도 확인이 어렵네요.

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +파드를 조회하면 당연히 초기화 컨테이너가 비정상 종료된걸 확인할 수 있습니다. `restartPolicy: Never`이므로 시간이 지나도 파드는 재할당 되지 않습니다.
재할당 -> 재시작

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +3. restartPolicy: Always(종료된 경우 항상 컨테이너 재실행)
initContainer의 restartPolicy가 Always인 경우 restartPolicy 값들 중 어떤 것과 동일하게 동작하는건가요?

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +### LimitRange
LimitRange는 현재 PR 내용과는 관련이 없습니다.
내용 제거해주시고 pod내 리소스제한에 대해서만 작성해주세요.
PR과 무관한 내용은 리뷰하지 않겠습니다.

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +[1. 파드 기본 개념](#파드-기본-개념)
목차가 전혀 정리되어있지 않네요.

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +### ImagePullPolicy
ImagePullPolicy 에 따라 Image가 업데이트된 경우 Pod 재시작이나 Pod를 새로 배포하는경우 Image ID가 어떻게 되는지 확인해보면 좋겠네요.

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +이 결과로 봤을 때 이 파드는 1개 이상의 컨테이너가 실행 중이므로 `Running` 상태이며 각 컨테이너는 다음과 같은 상태입니다.
phase가  Running 이지만 해당 파드가 정상이라고 볼 수 있을까요? kubectl은 NotReady로 보여지므로 문제있는 파드라고 보고 나중에 이런 상태의 파드가 존재한다면 트러블슈팅이 필요합니다.
kubectl describe보다 kubectl get  --o yaml 이나 json으로 pod 전체 스펙을 확인하는 것이 더 좋을 것 같습니다.
```json
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-24T02:48:08Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-24T02:47:59Z",
                "message": "containers with unready status: [failed-container completed-container]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-24T02:47:59Z",
                "message": "containers with unready status: [failed-container completed-container]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-24T02:47:59Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "containerd://badda170bce9db77ca92a9091167a33b0af780d1c9ed5bb7ccb977c6396f35b2",
                "image": "docker.io/library/busybox:latest",
                "imageID": "docker.io/library/busybox@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7",
                "lastState": {},
                "name": "completed-container",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://badda170bce9db77ca92a9091167a33b0af780d1c9ed5bb7ccb977c6396f35b2",
                        "exitCode": 0,
                        "finishedAt": "2024-06-24T02:48:43Z",
                        "reason": "Completed",
                        "startedAt": "2024-06-24T02:48:38Z"
                    }
                }
            },
            {
                "containerID": "containerd://af7361be62905d95d64e95f3296b02f621e83b493c0d3734f25c4c7bcd6fff19",
                "image": "docker.io/library/busybox:latest",
                "imageID": "docker.io/library/busybox@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7",
                "lastState": {
                    "terminated": {
                        "containerID": "containerd://0431b5321f6202c924f59225acbdad8712c21d389bbc6623a0d875ebc485bd86",
                        "exitCode": 1,
                        "finishedAt": "2024-06-24T02:49:28Z",
                        "reason": "Error",
                        "startedAt": "2024-06-24T02:49:28Z"
                    }
                },
                "name": "failed-container",
                "ready": false,
                "restartCount": 4,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://af7361be62905d95d64e95f3296b02f621e83b493c0d3734f25c4c7bcd6fff19",
                        "exitCode": 1,
                        "finishedAt": "2024-06-24T02:50:15Z",
                        "reason": "Error",
                        "startedAt": "2024-06-24T02:50:15Z"
                    }
                }
            },
            {
                "containerID": "containerd://4921c9e73630bd7908d8daf7462069b19ab06377fd260be11a0c5b649fa95dfb",
                "image": "10.60.160.121:5000/proxyv2:1.18.5",
                "imageID": "10.60.160.121:5000/proxyv2@sha256:db29d2eaeaaa1b930b139c416656408c78d20bd6673f21d98a681a4d748ae83b",
                "lastState": {},
                "name": "istio-proxy",
                "ready": true,
                "restartCount": 0,
                "started": true,
                "state": {
                    "running": {
                        "startedAt": "2024-06-24T02:48:09Z"
                    }
                }
            },
            {
                "containerID": "containerd://1d0003e54828fd32cf295a822096df87ec46c9b9417ae5047e869f336edee3ad",
                "image": "docker.io/library/busybox:latest",
                "imageID": "docker.io/library/busybox@sha256:9ae97d36d26566ff84e8893c64a6dc4fe8ca6d1144bf5b87b2b85a32def253c7",
                "lastState": {},
                "name": "running-container",
                "ready": true,
                "restartCount": 0,
                "started": true,
                "state": {
                    "running": {
                        "startedAt": "2024-06-24T02:48:32Z"
                    }
                }
            }
        ],
        "hostIP": "10.60.160.122",
        "initContainerStatuses": [
            {
                "containerID": "containerd://0eca4844b6cdfa55ae8f6f4e9c8615e03f37290e601ff93f96f924f5779cfae7",
                "image": "10.60.160.121:5000/proxyv2:1.18.5",
                "imageID": "10.60.160.121:5000/proxyv2@sha256:db29d2eaeaaa1b930b139c416656408c78d20bd6673f21d98a681a4d748ae83b",
                "lastState": {},
                "name": "istio-init",
                "ready": true,
                "restartCount": 0,
                "state": {
                    "terminated": {
                        "containerID": "containerd://0eca4844b6cdfa55ae8f6f4e9c8615e03f37290e601ff93f96f924f5779cfae7",
                        "exitCode": 0,
                        "finishedAt": "2024-06-24T02:48:06Z",
                        "reason": "Completed",
                        "startedAt": "2024-06-24T02:48:03Z"
                    }
                }
            }
        ],
        "phase": "Running",
        "podIP": "172.32.127.12",
        "podIPs": [
            {
                "ip": "172.32.127.12"
            }
        ],
        "qosClass": "Burstable",
        "startTime": "2024-06-24T02:47:59Z"
    }
```

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +- Running
kubectl
- Running
- Waiting/Terminated: 계속 재실행
- Terminated(Complted): 작업 완료 후 종료
- 
무슨 의미인지 모르겠네요.

2024-06-24 02:59 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +### 디플로이먼트 배포하고 다양한 방식으로 조회
디플로이먼트도 현재 PR 과 무관하므로 리뷰하지 않겠습니다.

2024-06-24 04:00 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +[1. 파드 기본 개념](#파드-기본-개념)
넵 알겠습니다.
주제 별로 목차 정리하겠습니다.

2024-06-24 04:51 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +[1. 파드 기본 개념](#파드-기본-개념)
> 주제별로 목차를 묶어서 보여주세요. 목차가 있어도 확인이 어렵네요.

주제별로 목차를 정리했습니다.

목차대로 내용의 위치를 조정하면서 변경사항이 많이 생겼습니다.
리뷰를 진행하기 불편하면 내용이 다 정리된 후 목차를 정리하겠습니다.

2024-06-24 04:55 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +파드를 조회하면 당연히 초기화 컨테이너가 비정상 종료된걸 확인할 수 있습니다. `restartPolicy: Never`이므로 시간이 지나도 파드는 재할당 되지 않습니다.
문구 수정하여 반영했습니다.

2024-06-24 05:02 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +3. restartPolicy: Always(종료된 경우 항상 컨테이너 재실행)
InitContainer에서 restartPolicy가 Always인 경우 OnFailure와 동일하게 동작합니다.
InitContainer가 성공한 경우, 초기화 컨테이너는 종료 후 재실행되지 않습니다.
InitContainer가 실패한 경우, 초기화 컨테이너는 재실행됩니다.

2024-06-24 05:03 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +### LimitRange
> LimitRange는 현재 PR 내용과는 관련이 없습니다. 내용 제거해주시고 pod내 리소스제한에 대해서만 작성해주세요. PR과 무관한 내용은 리뷰하지 않겠습니다.

LimitRange 내용 Pod.md에서 별도의 md파일로 분리하였습니다.

2024-06-24 05:06 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +### LimitRange
LimitRange는 따로 리소스제한 에서 다룰 오브젝트로 현재 pod PR에서는 내용 제거해주세요.

2024-06-24 05:08 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +### LimitRange
> LimitRange는 따로 리소스제한 에서 다룰 오브젝트로 현재 pod PR에서는 내용 제거해주세요.

알겠습니다. pod와 관련이 없으면 삭제하겠습니다.

2024-06-24 05:51 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +이 결과로 봤을 때 이 파드는 1개 이상의 컨테이너가 실행 중이므로 `Running` 상태이며 각 컨테이너는 다음과 같은 상태입니다.
> phase가 Running 이지만 해당 파드가 정상이라고 볼 수 있을까요? kubectl은 NotReady로 보여지므로 문제있는 파드라고 보고 나중에 이런 상태의 파드가 존재한다면 트러블슈팅이 필요합니다. 

이런 문제를 방지하기 위해 아래와 같은 단계를 더 추가할 수 있는걸 알았습니다.
1. 라이브니스 프로브 추가
2. 모니터링 도구 추가

> kubectl describe보다 kubectl get --o yaml 이나 json으로 pod 전체 스펙을 확인하는 것이 더 좋을 것 같습니다.

kubectl describe pod <pod-name>
- 사람이 읽기 쉬운 형식으로 파드의 자세한 내용을 출력하며, `이벤트 타임라인`을 제공합니다.
kubectl get pod <pod-name> -o yaml
- 파드의 `모든 세부 정보(전체 스펙과 현재 상태)`를 구조화된 형식으로 제공합니다.
pod 스펙을 확인할 때 kubectl get pod <pod-name> -o yaml 명령을 더 활용하겠습니다.

2024-06-24 06:00 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +- Running
```YAML
apiVersion: v1
kind: Pod
metadata:
  name: pod-status
spec:
  restartPolicy: OnFailure
  containers:
  - name: running-container
    image: busybox
    command: ["sh", "-c", "while true; do echo Running...; sleep 10000; done"]
  - name: failed-container
    image: busybox
    command: ["sh", "-c", "exit 1"]
  - name: completed-container
    image: busybox
    command: ["sh", "-c", "echo Hello, World!; sleep 5"]
```
파드에서 실행중인 각 컨테이너의 상태를 설명하는데 설명이 부실했습니다.

아래와 같이 수정했습니다.

```
이 결과로 봤을 때 이 파드는 1개 이상의 컨테이너가 실행 중이므로 `Running` 상태이며 파드내에 각 컨테이너는 다음과 같은 상태입니다.
- running-container
  - Running 상태이며, 정상적으로 동작하고 있습니다.
- failed-container
  - Waiting/Terminated 상태이며, 컨테이너가 재실행 중 입니다.
- completed-container
  - Terminated(Complted): 작업 완료 후 종료되었습니다.

하지만 이 파드는 Running 상태를 가지지만 정상적이라고 보기 힘듭니다.
이런 문제가 있는 파드를 감지하기 위해선 다음과 같은 단계를 추가해야합니다.
1. 라이브니스 프로브 사용
2. 재시작 정책
3. 모니터링 및 알림 도구 사용
```

2024-06-24 07:36 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +[1. 파드 기본 개념](#파드-기본-개념)
컨테이너는 파드 내 목차로 제공되어야하지만 정리한대로 보겠습니다. 목차는 더이상 수정안해도됩니다.

2024-06-24 08:22 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +```YAML
리소스 제한이 넘는 경우에 대한 결과가 있으면 좋겠네요.

2024-06-24 08:22 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +- Running
restartPolicy는 기본 값이 Always이기 때문에 completed되어도 다시 재시작할텐데 completed-container는 재시작 안하나요?

2024-06-24 15:25 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +- Running
> restartPolicy는 기본 값이 Always이기 때문에 completed되어도 다시 재시작할텐데 completed-container는 재시작 안하나요?

completed-container도 재시작합니다. 
`completed-container`의 실행 시간이 매우 짧게 설정되어 있어 파드가 1/3로 되어 있는걸 보고 재실행이 안되는 걸로 학습했습니다.
학습할 때 설정값을 더 세심하게 확인하겠습니다. 죄송합니다.

아래는 해당 파드를 조회한 값입니다.
```
 completed-container:
    Command:
      sh
      -c
      echo Hello, World!; sleep 5
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 25 Jun 2024 00:07:23 +0900
      Finished:     Tue, 25 Jun 2024 00:07:28 +0900
    Ready:          False
    Restart Count:  5
```

아래와 같이 문서 수정하였습니다.


파드 목록을 조회하면 1개 컨테이너가 READY 상태이고 그 이후 1개의 컨테이너는 작업 완료 후 재실행 상태라 1개 ~ 2개 READY로 된걸 확인할 수 있습니다.

```
pod-status                                         0/3     ContainerCreating   0             3s
pod-status                                         2/3     Error               0             7s
pod-status                                         2/3     Error               1 (5s ago)    10s
pod-status                                         2/3     CrashLoopBackOff    1 (2s ago)    11s
pod-status                                         2/3     Error               2 (18s ago)   27s
pod-status                                         1/3     NotReady            2 (11s ago)   38s
pod-status                                         2/3     CrashLoopBackOff    3 (3s ago)    40s
pod-status                                         2/3     Error               4 (17s ago)   54s
pod-status                                         2/3     CrashLoopBackOff    4 (13s ago)   66s
pod-status                                         1/3     NotReady            4 (17s ago)   70s
pod-status                                         1/3     CrashLoopBackOff    4 (13s ago)   82s
pod-status                                         2/3     CrashLoopBackOff    5 (15s ago)   84s

해당 파드는 1개가 정상적 실행, 1개 실패, 1개는 정상 종료 후 재실행 상태를 가지고 있습니다.
1개는 기본적으로 실행하고 있지만, `completed-container`가 재실행 하며 실행 상태일 때 2/3으로 표시된 걸 알 수 있습니다.
```

실행한 결과에서 필요한 부분만 복사했습니다. 재시작 정책이 `OnFailure`라서 에러가 발생한 경우만 재실행됩니다.

이 결과로 봤을 때 이 파드는 1개 이상의 컨테이너가 실행 중이므로 `Running` 상태이며 파드내에 각 컨테이너는 다음과 같은 상태입니다.
- running-container
  - Running 상태이며, 정상적으로 동작하고 있습니다.
- failed-container
  - Waiting/Terminated(Error) 상태이며, 컨테이너가 재실행 중 입니다.
- completed-container
  - Waiting/Terminated(Complted): 작업 완료 후 재시작합니다.

2024-06-26 00:44 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +```YAML
> 리소스 제한이 넘는 경우에 대한 결과가 있으면 좋겠네요.

리소스 제한(CPU, Memory)을 넘은 상황에 대한 예제를 추가 했습니다.
문서에 아래와 같이 추가했습니다.

```Python
import time

def allocate_memory(size_in_mb):
    size_in_bytes = size_in_mb * 1024 * 1024
    memory_holder = bytearray(size_in_bytes)
    print(f"Allocated {size_in_mb} MB of memory.")
    time.sleep(60)  # Keep the memory allocated for 60 seconds

if __name__ == "__main__":
    size_in_mb = int(input("Enter the amount of memory to allocate in MB: "))
    allocate_memory(size_in_mb)
```
입력받은 숫자 만큼의 <n>mb를 할당받는 스크립트 입니다.

```YAML
apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
spec:
  containers:
  - name: memory-hog
    image: python:3.9
    command: ["python", "-c", "import time; time.sleep(36000)"]
    resources:
      limits:
        memory: "1024Mi"
      requests:
        memory: "512Mi"
```
`1024Mi`만큼 리소스가 제한된 파드입니다.

```
#kubectl top pod memory-hog
NAME         CPU(cores)   MEMORY(bytes)   
memory-hog   1m           11Mi 
```
현재 사용중인 메모리는 `11Mi`입니다. 

![image](https://github.com/hotkimho/edu-backend/assets/26193155/d3a5fea7-6334-427d-8498-b8ba8b039494)


`1000MB`를 할당하고 다시 메모리 사용량을 조회한 결과입니다.
```
# kubectl top pod memory-hog
NAME         CPU(cores)   MEMORY(bytes)   
memory-hog   27m          1016Mi
```

`1024Mi`를 넘지 않았고, 정상적으로 스크립트가 동작된 걸 확인할 수 있습니다. 여기서 조금 더 많은 메모리를 할당해보겠습니다.

![image](https://github.com/hotkimho/edu-backend/assets/26193155/e7d15c4c-7c74-4373-a806-e1ef240ddae6)

`1024Mi`를 넘는 메모리를 할당하자 프로세스가 강제로 종료되었습니다.

컨테이너의 커널이 메모리 부족(OOM)이 활성화 되고 메모리를 할당 받으려고 했던 프로세스(이 예제에서는 1개) 중 하나를 종료한 걸 확인할 수 있었습니다.

```
쿠버네티스 공식문서에 의하면 CPU 제한을 초과하는 요청이 온 경우, 초과하는 요청을 대기 상태로 만듭니다(다음 스케줄링 까지 대기)
이 후 다른 작업이 완료 되면 대기 상태에 있던 작업을 이어서 처리하게 됩니다.

CPU에 부하를 주어 CPU 사용량을 테스트 했을 때, 일정 사용량을 넘지 않았습니다.
그리고 부하를 주는 프로그램의 로그 출력이 잠시나마 멈췄습니다.

이런 상황으로 봤을 때 부하(CPU 제한)를 초과하는 요청이 왔을 때, 대기 상태가 되었고 이 때 부하 프로그램의 로그가 잠시 멈춘게 아닐까 싶습니다.

이런 상황으로 봤을 때 공식 문서에 나온대로 동작이 실행됐다고 봐도 될 것같습니다.
```

2024-06-27 03:01 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +```YAML
cpu throttling이 걸리는 것 같네요. 퍼포먼스를 낮춰서 응답이 느려지는 것 같아요.
부하테스트 로그에서도 로그가 더이상 없다하니 응답이 오지 않아서 부하테스트 툴 자체도 응답이 쌓여 더이상 요청을 보내지 않도록되어있나 싶네요.
cpu throttling으로 container restart 하지 않으나 만약 지금처럼 퍼포먼스에 문제가 있다면 livenessprobe를 활용하여 restart하도록하는 것도 방법일 것 같네요.
확인하시느냐고 고생하셨습니다.

2024-06-27 04:01 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +```YAML
cpu throttling로 요청을 수행할 수 없는 상태인 경우

livenessprobe로 HTTP 요청을 보내서 응답이 없으면 컨테이너를 재시작한다.

이런 흐름으로 말씀하신걸까요?

2024-06-27 04:25 UTC, devmjkim commented on docs/kubernetes-extension/pod.md
> +```YAML
네 결국 정상적이지 않으니 restart되도록 livenessprobe를 사용하는 것도 방법일 것 같네요.

2024-06-27 04:26 UTC, hotkimho commented on docs/kubernetes-extension/pod.md
> +```YAML
네 알겠습니다.

감사합니다.

2024-06-27 04:37 UTC, devmjkim approved these changes

2024-06-28 02:26 UTC, devmjkim commented
@hotkimho 님 squash로 병합해주세요. 병합 메시지는 모든 커밋 메시지가 들어가지 않도록 정리해서 넣어주세요.

2024-06-28 03:47 UTC, merged

2024-06-28 03:48 UTC, hotkimho commented
> @hotkimho 님 squash로 병합해주세요. 병합 메시지는 모든 커밋 메시지가 들어가지 않도록 정리해서 넣어주세요.

머지 승인 받아서 머지합니다.